### ISSUE TITLE
Can't detect full stop at the end of the sentance

### ISSUE THREAD

**Issue by darkmatter18** [swapagarwal/geeksay#122]
Sentance without a full stop is detected like this.

![Without full stop](https://user-images.githubusercontent.com/30409045/66463612-0ff42600-ea9b-11e9-8310-4fbe07d85533.png)

Sentance with a full stop is like this.

![With Full stop](https://user-images.githubusercontent.com/30409045/66463669-2dc18b00-ea9b-11e9-9e8a-a64bde489044.png)

It is looking bad when the sentence misses the word with a full stop. So I think it's an issue.
If you think the same, please let me work on it.

**Comment by barosch47** [comment]
Hi i would like to fix this.
