### ISSUE TITLE
Test for duplicates

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/geeksay#209]
Add a test that passes only when all the entries in the translations object are unique.

**Comment by clariokids** [comment]
it's going to changes all your translations object construction

**Comment by dopecodez** [comment]
Is this issue done? If not I'll take it up. We should ideally have the test run on the translations object and the quotes object and fail if it sees a duplicate. Could i take this up?

**Comment by ulises-lara** [comment]
Hey @dopecodez !
Have you found time to work on this?
I am looking into it as well, but please let me know if you've already started work on it, or if you need a helping hand!

**Comment by dopecodez** [comment]
Hey @ulises-lara , Actually I didn't take this up as the thread seemed inactive. You are welcome to try submitting a PR provided that this still isn't solved. @swapagarwal

**Comment by Dolidodzik** [comment]
Is this issue still avaiable? @swapagarwal

**Comment by gr8temi** [comment]
Hey @swapagarwal  I'll love to take up this issue if it's still available

**Comment by speckworks** [comment]
Is this still open?  The site doesn't seem to be deployed currently?

**Comment by Theys96** [comment]
Hi! I think I solved this issue for the current code by parsing the library code (see my pull request).
