### ISSUE TITLE
Create a copy button

### ISSUE THREAD

**Issue by dk3775** [swapagarwal/geeksay#355]
We need a copy to clipboard button which automatically copies the translated text to user's clipboard. This button can be placed beside the twitter button and should have style like random text button.

Anyone who wants to work on this can tag me here and get this issue assigned to themself.

**Comment by abitsalihu** [comment]
@dk3775 I would like to work on this issue :)

**Comment by dk3775** [comment]
@abitsalihu you are good to go I am assigning on this!

**Comment by abitsalihu** [comment]
@dk3775 I finished this issue, but I think I made a mistake to what should be copied. I made the copy button to copy the random quote that is generated or should it copy the : Random Translation: (this part that is inside here) ?

If you could tell me if i did it correctly or I should make changes so I can move on with the PR. :)

**Comment by abitsalihu** [comment]
@dk3775 I read the Issue again, and I think I understand what needed to be copied (the translated quote that is generated from the random quote)!

Below is a video of how the "copy button" works now: 
Please tell me if this is correct so I can go ahead and make a PR.

https://user-images.githubusercontent.com/94648837/191016127-4ddced47-ad35-4563-9c2a-d4c2455b5f31.mov

**Comment by dk3775** [comment]
@abitsalihu bro actually we had to copy whatever text is there in translated textbox, I guess just changing the js object will do the needful.

Hope you understood that, else just ping me again anytime!!

**Comment by abitsalihu** [comment]
@dk3775 I already made a PR yesterday, can you please check it out and tell me what's wrong.
There is a video attached with it to see how it works!

**Comment by dk3775** [comment]
@abitsalihu I already checked it that is copying the text from the first textbox but it needs to be copying text from the second text box.

**Comment by dk3775** [comment]
@abitsalihu ooh my bad I didn't check it correctly it's working perfectly fine, thanks!

**Comment by abitsalihu** [comment]
@dk3775 please check the latest commit I did on the PR. :)

**Comment by dk3775** [comment]
Hello @abitsalihu you did great work adding that button, 
Still I think we need better styling to the button.

**Comment by abitsalihu** [comment]
@abitsalihu thank you, I styled it the same as the `random button` as I was told so. :)

**Comment by dk3775** [comment]
@abitsalihu I know but now think it does not go with the flow :-|

**Comment by RohanTheProgrammer** [comment]
Hi @dk3775 I am working on the copy button trying to amke it a little bit better. I am improving the alert and trying to make the copy button look more natural to the page.

**Comment by aharna** [comment]
hey! I would like to work on this issue

**Comment by RohanTheProgrammer** [comment]
Hi @aharna
Well I have made a version of copy button and made a PR. Still both of us will have to wait for @dk3775 for his reponse.

**Comment by dk3775** [comment]
Hello @RohanTheProgrammer and @aharna I am on it, will update soon!

**Comment by dk3775** [comment]
This issue is solved by #369 from @RohanTheProgrammer. And is now closed.
