### ISSUE TITLE
Improve the Mobile Responsive Version

### ISSUE THREAD

**Issue by Ayush-Kanduri** [swapagarwal/geeksay#380]
Hey, I feel the mobile responsive version of the website is congested. The buttons shouldn't stick with the Geeks Output box as there's no breathable space. 
I think the buttons should be below the box. 
Also requires some minor tweaks to the responsive version.

![1](https://user-images.githubusercontent.com/76626529/193489307-aedb5498-f3f0-4e71-8dfb-1e0c525b96c0.png)

If you Green Light this issue, can I work on it?

**Comment by Ayush-Kanduri** [comment]
If you Green Light this issue, can I work on it?

**Comment by dk3775** [comment]
Actually, the new copy button is creating this issue, Although you can contribute here for the same issue -> #369.

**Comment by dk3775** [comment]
@Ayush-Kanduri Still you do have a green light..

**Comment by Ayush-Kanduri** [comment]
> @Ayush-Kanduri Still you do have a green light.. But the buttons and the output box is fixed by #392 .

Thanks, Dhyey 😀 I'll see if something is there that needs to be done.

**Comment by dk3775** [comment]
Sure !

**Comment by dk3775** [comment]
@Wodlfvllf yes you can go on!

**Comment by Ayush-Kanduri** [comment]
Hi Dhyey, I have worked on this issue & made a PR #408 . 

Kindly Merge my PR, I would be glad.

**Comment by dk3775** [comment]
#408 Fixed this issue but still I think we can work around the social buttons after the translated textbox and only copy button above the text box,
Furthermore, we can add a share to Facebook button also.

**Comment by Ayush-Kanduri** [comment]
> #408 Fixed this issue but still I think we can work around the social buttons after the translated textbox and only copy button above the text box, Furthermore, we can add a share to Facebook button also.

Yes that's what I was thinking, like copy button to be above the translation box and social buttons to be below the translation box.
I'll see to it, what could be done.

**Comment by dk3775** [comment]
We could also bring the Copy button inline with the text then, it would look better I guess.

**Comment by Ayush-Kanduri** [comment]
> We could also bring the Copy button inline with the text then, it would look better I guess.

What about, if we put the copy button inside the translate box?

**Comment by dk3775** [comment]
I think the button looks great outside the box.

**Comment by gerasaka** [comment]
Hello, can I work for this too?

**Comment by gerasaka** [comment]
I also have some suggestions

1. I think the "random quote" button and the "tweet" button would be better if they had the same right-alignment
<img src="https://user-images.githubusercontent.com/68799154/194112137-3dac0c99-f3f5-4a09-b5d4-3276dd8d4069.png" width="500"/>

2. "tweet" button hover looks like it could be improved
<img src="https://user-images.githubusercontent.com/68799154/194112975-498ca938-69d6-4290-8ecb-af19e7329e51.png" width="200"> <img src="https://user-images.githubusercontent.com/68799154/194112889-0d050e9b-cb45-472a-99ab-c4dee0fbcd14.png" width="200" />

4. it looks like the buttons have inconsistent font size
5. fix margin for smaller viewport
<img src="https://user-images.githubusercontent.com/68799154/194113347-b7699bb4-0581-4ada-86c1-dfa07ef7294c.png" width="500" />

**Comment by dk3775** [comment]
@gerasaka Go on !

**Comment by Mayank7225** [comment]
can i work on this?

**Comment by dk3775** [comment]
@Mayank7225 yes

**Comment by ferrorenan** [comment]
I'd like to work with it, can I!?

**Comment by Ayush-Kanduri** [comment]
Hi Dhyey, Added the Social Buttons + Removed some existing errors as well.

All mentioned in Pull Request #440

**Comment by Ayush-Kanduri** [comment]
Issue Completed
