### ISSUE TITLE
BUTTON RANDOM QUOTE AND COPY QUOTE NOT WORKING 

### ISSUE THREAD

**Issue by rakshitdabral** [swapagarwal/geeksay#386]
These is an error with the random quote button with two line of code written in index.js where as copy button doesn't really produces any error but is not actually working

**Comment by rakshitdabral** [comment]
i fixed the issue for now

**Comment by rakshitdabral** [comment]
#387

**Comment by dk3775** [comment]
Done the issue is solve as the above PR is accepted.
