### ISSUE TITLE
I want to update the regular function with the arrow functions.

### ISSUE THREAD

**Issue by rahulgithub-web** [swapagarwal/geeksay#430]
Please assign me this task as want to contribute on this project and want to make changes in this poject like want to replace var with let and const as it is more faster than var variable and also for the security concerns.

**Comment by Flanker-shyam** [comment]
Assign this task to me, I always use arrow functions in my projects as they are convenient to use and easy to write.

**Comment by dk3775** [comment]
Hey guys you can create PRs proposing your changes we'll merge it if its valid.

**Comment by rahulgithub-web** [comment]
ok sir thank you I will follow the same.
