### ISSUE TITLE
Share button not displaying. 

### ISSUE THREAD

**Issue by chase-west** [swapagarwal/geeksay#483]
This should display on website 
![image](https://github.com/swapagarwal/geeksay/assets/57733840/acfc9d17-425b-4759-a7a7-8d43409ff082)

It does not display on website 
![image](https://github.com/swapagarwal/geeksay/assets/57733840/4e19efe1-abb3-4d87-85e4-810a556a04ee)

**Comment by chase-west** [comment]
When forking and cloning the repo it displays locally. Is the website not the latest version? 
![image](https://github.com/swapagarwal/geeksay/assets/57733840/90b72a2d-9e96-4c7d-9b2f-bd9ed77e1c5c)

**Comment by dk3775** [comment]
It's displaying properly please check again!

**Comment by chase-west** [comment]
> It's displaying properly please check again!

You are correct so sorry it appears my ad blocker was blocking it on my end.
