### ISSUE TITLE
Handle punctuations

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/geeksay#63]
Punctuations like comma should not be considered part of the word while translating, e.g. `roses are red, violets are blue` should translate to `roses are ##ff0000, violets are #0000ff` and not `roses are red, violets are #0000ff`
<img width="632" alt="Screenshot 2019-10-02 22 07 29" src="https://user-images.githubusercontent.com/2833845/66063462-0893c080-e561-11e9-8a4c-501c4f319e90.png">

**Comment by itnug987** [comment]
@swapagarwal  I want to work on this issue.

**Comment by jeffinnes** [comment]
@swapagarwal I would like to work on this issue if that's okay!

**Comment by ccoffey1** [comment]
Ah! I just noticed the issue has a PR open for it already. Feel free to go with the one that was opened prior, still went ahead with making mine for Hacktoberfest :>
