### ISSUE TITLE
unit test implementation

### ISSUE THREAD

**Issue by pedramp** [swapagarwal/geeksay#75]
Seems that we don't have `unit test` here :( 

suggestion tests: 
* testing all translations, quotes
* multi-line
* inside html tags
* multilingual notes
* camelcase 
* markdown format 
* space and half-space chars 
* unicode test
* ...

**Comment by swapagarwal** [comment]
Go for it! 💯

**Comment by pedramp** [comment]
added to my list, I'll send PR soon.

**Comment by pedramp** [comment]
submitted my PR #91
