### ISSUE TITLE
npm/yarn support

### ISSUE THREAD

**Issue by pedramp** [swapagarwal/geeksay#81]
## module 
 implementing exports compability, that user can run it easily in Node env. 
```
if(typeof exports === 'object' && typeof module !== 'undefined' )
 module.exports = geeksay;
```
## package.json
adding `package.json` file. 

## npm register
* registering geeksay as npm module that user can install it by npm/yarn 
`npm i geeksay`
```
const geeksay = require('geeksay');
const foo = geeksay('I like geeksay'); // i <3 geeksay
```

**Comment by swapagarwal** [comment]
[published on npm!](https://www.npmjs.com/package/geeksay)
This would need some changes to work like you mentioned in the above example, right?

**Comment by swapagarwal** [comment]
So on RunKit (https://npm.runkit.com/geeksay),
single words are working fine but sentences are not:
```
const geeksay = require('geeksay');
const foo = geeksay('save'); // ctrl+s
const bar = geeksay('i love geeksay'); // i love geeksay
```

**Comment by pedramp** [comment]
good job 👍 
I'll send my PR by end of today to support sentences :)

**Comment by pedramp** [comment]
PR #89  submitted, please review it.

**Comment by swapagarwal** [comment]
Working as expected:
```
const geeksay = require('geeksay');
const foo = geeksay('save'); // ctrl+s
const bar = geeksay('i love geeksay'); // i <3 geeksay
```
